grid_map_topic: /grid_test/grid_map
grid_map_visualizations:
  - name: density_points
    type: point_cloud
    params:
     layer: density
  - name: density_grid
    type: occupancy_grid
    params:
     layer: density
     data_min: 0.08
     data_max: -0.16
